### PR TITLE
Update CH09_ScriptingInAHypermediaApplication.adoc

### PR DESCRIPTION
**Pull request by lucaslugao**
Fix vanilla js example so the function actually uses the subtree to query for new elements.

### CODE REVIEW

**Comment by vikstrous2** [comment]
I ran into the same bug. Please accept this fix. Without it, the buttons work on first page load, but not after navigating away (ex. to one of the contact view pages) and navigating back to the index page.

**Comment by ramiro** [comment]
#107 is a duplicate opened after this one. But it also includes an additional JS formatting error fix so I'd suggest to close this PR.

**Comment by lucaslugao** [comment]
I'm ok closing this if the other PR gets submitted. It's a bit sad that this remained unanswered since June :(

**Comment by lucaslugao** [comment]
Raised an issue about the lack of review in either PR: https://github.com/bigskysoftware/hypermedia-systems/issues/110

**Review by dz4k — APPROVED** [review]

**Pull request merged**
